#!/bin/bash -e

echocol() { echo -e "\033[32m*** $@...\033[0m"; }

if [ ! -r ./bin/tm ]; then
	echocol "Installing tristo-mietitore"
	curdir=$(pwd)
	mkdir -p ./var/
	cd ./var
	git clone https://github.com/mapio/tristo-mietitore.git >/dev/null 2>&1
	cd tristo-mietitore
	./bin/mkdist
	mv ./bin/tm ../../bin
	cd ..
	rm -rf tristo-mietitore
	cd $curdir
fi

tests="makefiles prepare"

for t in $tests; do
	echocol $t
	./test/$t
done
