#!/bin/bash -e

echocol() { echo -e "\033[32m*** $@...\033[0m"; }

if [ ! -r ./var/tm.zip ]; then
	echocol "Skipping tests depending on tristo-mietitore"
	tests="makefiles"
else
	tests="makefiles prepare"
fi

for t in $tests; do
	echocol $t
	./test/$t
done
