#!/bin/bash -e

echocol() { echo -ne "\033[31m$@...\033[0m "; }

tempdir=$(mktemp -d /tmp/cu-XXXXXXXXX) || exit 1
make_file_size=$(\ls -l ./support/Makefile | tr -s ' ' | cut -d' ' -f5)
readme_file_size=$(\ls -l ./support/LEGGIMI.txt | tr -s ' ' | cut -d' ' -f5)
#echo "[Makefile size: $make_file_size, LEGGIMI.txt size: $readme_file_size]"

cp -r ./test/srcdir $tempdir
export EXERCISES_DIR=$tempdir/srcdir
mkdir -p /tmp/cu_test/uploads
./bin/prepare_confs $EXERCISES_DIR /tmp/cu_test/uploads >/dev/null 2>&1

export PYTHONPATH=./bin/tm

echocol "Tristo mietitore tar file"
if diff -u <(
( python <<EOF
from tm.mkconf import tar, untar, lstar
l = {}
execfile( '$EXERCISES_DIR/pc/srcdir-tm.py', l )
lstar( l[ 'TAR_DATA' ] )
EOF
) | awk '{print $1, $3, $6}' | sort ) <(cat <<EOF | sort
-r-------- 0 esercizio-1/Testo.txt
-r-------- 0 esercizio-2/Testo.txt
-r-------- 0 esercizio-3/Testo.txt
-r-------- $readme_file_size LEGGIMI.txt
-r-------- 2 esercizio-1/args-1.txt
-r-------- 2 esercizio-1/input-1.txt
-r-------- 2 esercizio-1/output-1.txt
-r-------- 2 esercizio-2/args-1.txt
-r-------- 2 esercizio-2/input-1.txt
-r-------- 2 esercizio-2/output-1.txt
-r-------- 2 esercizio-3/args-1.txt
-r-------- 2 esercizio-3/input-1.txt
-r-------- 2 esercizio-3/output-1.txt
-r-------- $make_file_size bin/Makefile
-r-x------ 0 bin/
-r-x------ 39 bin/aggiorna
-r-x------ 41 bin/identifica
-r-x------ 81 bin/consegna
-rwx------ 0 esercizio-1/
-rwx------ 0 esercizio-2/
-rwx------ 0 esercizio-3/
EOF
); then
	echo OK
else
	echo FAIL
	exit 1
fi

echocol "See You tar file"
if diff <(
( python <<EOF
from tm.mkconf import tar, untar, lstar
l = {}
execfile( '$EXERCISES_DIR/pc/srcdir-cu.py', l )
lstar( l[ 'TAR_DATA' ] )
EOF
) | awk '{print $1, $3, $6}' | sort ) <(cat <<EOF | sort
-r-------- 2 esercizio-1/args-1.txt
-r-------- 2 esercizio-1/args-1t.txt
-r-------- 2 esercizio-1/input-1.txt
-r-------- 2 esercizio-1/input-1t.txt
-r-------- 2 esercizio-1/output-1.txt
-r-------- 2 esercizio-1/output-1t.txt
-r-------- 2 esercizio-2/args-1.txt
-r-------- 2 esercizio-2/args-1t.txt
-r-------- 2 esercizio-2/input-1.txt
-r-------- 2 esercizio-2/input-1t.txt
-r-------- 2 esercizio-2/output-1.txt
-r-------- 2 esercizio-2/output-1t.txt
-r-------- 2 esercizio-3/args-1.txt
-r-------- 2 esercizio-3/args-1t.txt
-r-------- 2 esercizio-3/input-1.txt
-r-------- 2 esercizio-3/input-1t.txt
-r-------- 2 esercizio-3/output-1.txt
-r-------- 2 esercizio-3/output-1t.txt
-r-------- $make_file_size bin/Makefile
-r-x------ 0 bin/
-rwx------ 0 esercizio-1/
-rwx------ 0 esercizio-2/
-rwx------ 0 esercizio-3/
EOF
); then
	echo OK
else
	echo FAIL
	exit 1
fi

rm -rf $tempdir
