#!/bin/bash

( export MAKEFILES="$(pwd)/Makefile-student $(pwd)/Makefile-teacher"
make clean
make evals ) >/dev/null
echo "Adding to server download bundle..."
python ../../server/eegat/templates/client.py _t bundle '(bin/.*|Makefile|LEGGIMI.txt|esercizio-[0-9]+/(Testo|(input|output|args)-[0-9]+)\.txt)' >/dev/null >> ../../server/conf.py
echo "Adding to grader evaluation bundle..."
python ../../server/eegat/templates/client.py _t bundle 'esercizio-[0-9]+/(input|output|args)-.+\.txt' >> ../../grader/conf.py
